GUI/BigRememberGUI/Controllers/EventInYearsController.cs
using System.Web.Mvc;
using RememberUtility.Constant;
using RememberUtility.Extension;
using RememberUtility.HandleUtil;

namespace BigRememberGUI.Controllers
{
    public class EventInYearsController : Controller
    {
        private readonly EvenInYearUtil _evenInYearUtil;

        public EventInYearsController()
        {
            _evenInYearUtil = new EvenInYearUtil();
        }

        // GET: EventInYears
        public ActionResult Index()
        {
            return View(_evenInYearUtil.GetEventInYears());
        }

        // GET: EventInYears/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: EventInYears/Create
        public ActionResult Create()
        {
            var listConstantValue = typeof(CategoriesCountryOccuredConstant).GetAllPublicConstantValues<string>();
            listConstantValue.Sort();

            ViewBag.ListCountry = new SelectList(listConstantValue);

            return View();
        }

        // POST: EventInYears/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: EventInYears/Edit/5
        public ActionResult Edit(int id)
        {
            var listConstantValue = typeof(CategoriesCountryOccuredConstant).GetAllPublicConstantValues<string>();
            listConstantValue.Sort();

            ViewBag.EditListCountry = new SelectList(listConstantValue);

            return View();
        }

        // POST: EventInYears/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: EventInYears/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: EventInYears/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

GUI/BigRememberGUI/Views/EventInYears/Create.cshtml
@model ConnectionSampleCode.Model.EventInYear

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
      
        <div class="form-group">
            @Html.LabelFor(model => model.EventName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CountryOccured, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CountryOccured, ViewBag.ListCountry as SelectList, "--- Select Country ---", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CountryOccured, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventLink, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventLink, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventLink, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShortDescribe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShortDescribe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShortDescribe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "EventInYears")
</div>

GUI/BigRememberGUI/Views/EventInYears/Delete.cshtml
@model ConnectionSampleCode.Model.EventInYear

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EventYearId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventYearId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CountryOccured)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CountryOccured)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventLink)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventLink)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShortDescribe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShortDescribe)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastModifiedDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index", "EventInYears")
        </div>
    }
</div>

GUI/BigRememberGUI/Views/EventInYears/Details.cshtml
@model ConnectionSampleCode.Model.EventInYear

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EventYearId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventYearId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CountryOccured)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CountryOccured)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventLink)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventLink)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShortDescribe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShortDescribe)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastModifiedDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", "EventInYears", new {  id = Model.EventYearId }, null)|
    @Html.ActionLink("Back to List", "Index", "EventInYears")
</p>

GUI/BigRememberGUI/Views/EventInYears/Edit.cshtml
@model ConnectionSampleCode.Model.EventInYear

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
      @Html.HiddenFor(model => model.EventYearId)

        <div class="form-group">
            @Html.LabelFor(model => model.EventName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CountryOccured, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CountryOccured, ViewBag.EditListCountry as SelectList, "--- Select Country ---", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CountryOccured, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventLink, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventLink, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventLink, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShortDescribe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShortDescribe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShortDescribe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "EventInYears")
</div>

GUI/BigRememberGUI/Views/EventInYears/Index.cshtml
@model IEnumerable<ConnectionSampleCode.Model.EventInYear>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="text-center">List Events in year</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EventYearId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CountryOccured)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventLink)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShortDescribe)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastModifiedDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EventYearId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EventName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CountryOccured)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EventLink)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EventDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ShortDescribe)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastModifiedDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", "EventInYears", new {  id=item.EventYearId },null) |
            @Html.ActionLink("Details", "Details", "EventInYears", new { id = item.EventYearId }, null) |
            @Html.ActionLink("Delete", "Delete", "EventInYears", new { id = item.EventYearId }, null)
        </td>
    </tr>
}

</table>